apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: iam-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: 'https://github.com/Suraj01Dev/Automate-Orchestrate-Innovate-The-DevOps-Playbook-for-the-AI-Era.git'
        revision: main
        directories:
          - path: iam_policies/*
  template:
    metadata:
      name: '{{path.basename}}-iam'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Suraj01Dev/Automate-Orchestrate-Innovate-The-DevOps-Playbook-for-the-AI-Era.git'
        path: '.'
        targetRevision: main
        helm: 
          parameters:
            - name: serviceName
              value: '{{path.basename}}'
            - name: policiesFolder
              value: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
