apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-appset
  namespace: argocd
spec:
  # The generators field is used to define the clusters or namespaces where the application should be deployed.
  # This example uses a list generator to specify a single destination.
  generators:
  - list:
      elements:
      - cluster: in-cluster
        name: default
  template:
    metadata:
      name: '{{name}}-nginx'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: helm-guestbook

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      
